version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.neo4j:neo4j
    versions:
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: io.micrometer:micrometer-registry-prometheus
    versions:
    - 1.6.3
    - 1.6.4
    - 1.6.5
  - dependency-name: org.springframework.data:spring-data-r2dbc
    versions:
    - 1.3.0-GH-538-SNAPSHOT
    - 1.3.0-SNAPSHOT
  - dependency-name: org.testcontainers:kafka
    versions:
    - 1.15.1
    - 1.15.2
  - dependency-name: org.testcontainers:postgresql
    versions:
    - 1.15.1
    - 1.15.2
  - dependency-name: org.springframework.cloud:spring-cloud-dependencies
    versions:
    - Hoxton.SR10
    - Hoxton.SR9
  - dependency-name: com.thoughtworks.xstream:xstream
    versions:
    - 1.4.15
  - dependency-name: io.prometheus:simpleclient_pushgateway
    versions:
    - 0.9.0
- package-ecosystem: maven
  directory: "/discovery-service"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/edge-service"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.thoughtworks.xstream:xstream
    versions:
    - 1.4.15
- package-ecosystem: maven
  directory: "/friend-service"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.data:spring-data-r2dbc
    versions:
    - 1.3.0-GH-538-SNAPSHOT
    - 1.3.0-SNAPSHOT
  - dependency-name: org.testcontainers:postgresql
    versions:
    - 1.15.1
    - 1.15.2
  - dependency-name: org.testcontainers:kafka
    versions:
    - 1.15.1
    - 1.15.2
- package-ecosystem: maven
  directory: "/user-service"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.data:spring-data-r2dbc
    versions:
    - 1.3.0-GH-538-SNAPSHOT
    - 1.3.0-SNAPSHOT
  - dependency-name: org.testcontainers:kafka
    versions:
    - 1.15.1
    - 1.15.2
  - dependency-name: org.testcontainers:postgresql
    versions:
    - 1.15.1
    - 1.15.2
- package-ecosystem: maven
  directory: "/recommendation-service"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.neo4j:neo4j
    versions:
    - 4.2.2
    - 4.2.3
    - 4.2.4
